In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [26]:
df = pd.read_csv("tripdata2010.csv")

In [27]:
df

Duration           Start date             End date  \
0           1012  2010-09-20 11:27:04  2010-09-20 11:43:56   
1             61  2010-09-20 11:41:22  2010-09-20 11:42:23   
2           2690  2010-09-20 12:05:37  2010-09-20 12:50:27   
3           1406  2010-09-20 12:06:05  2010-09-20 12:29:32   
4           1413  2010-09-20 12:10:43  2010-09-20 12:34:17   
...          ...                  ...                  ...   
115592      2179  2010-12-31 23:20:32  2010-12-31 23:56:52   
115593       953  2010-12-31 23:21:57  2010-12-31 23:37:50   
115594       737  2010-12-31 23:27:28  2010-12-31 23:39:45   
115595       514  2010-12-31 23:37:38  2010-12-31 23:46:12   
115596     51962  2010-12-31 23:49:05  2011-01-01 14:15:08   

        Start station number                  Start station  \
0                      31208       M St & New Jersey Ave SE   
1                      31209                 1st & N St  SE   
2                      31600                  5th & K St NW   
3                      31600                  5th & K St NW   
4                      31100  19th St & Pennsylvania Ave NW   
...                      ...                            ...   
115592                 31110       20th St & Florida Ave NW   
115593                 31106       Calvert & Biltmore St NW   
115594                 31602        Park Rd & Holmead Pl NW   
115595                 31111                 10th & U St NW   
115596                 31111                 10th & U St NW   

        End station number                      End station Bike number  \
0                    31108                    4th & M St SW      W00742   
1                    31209                   1st & N St  SE      W00032   
2                    31100    19th St & Pennsylvania Ave NW      W00993   
3                    31602          Park Rd & Holmead Pl NW      W00344   
4                    31201                   15th & P St NW      W00883   
...                    ...                              ...         ...   
115592               31623  Columbus Circle / Union Station      W00859   
115593               31401           14th St & Spring Rd NW      W00914   
115594               31401           14th St & Spring Rd NW      W00973   
115595               31202                   14th & R St NW      W01119   
115596               31111                   10th & U St NW      W00771   

       Member type  
0           Member  
1           Member  
2           Member  
3           Member  
4           Member  
...            ...  
115592      Casual  
115593      Member  
115594      Member  
115595      Member  
115596      Casual  

[115597 rows x 9 columns]

In [28]:
df.head()

Duration           Start date             End date  Start station number  \
0      1012  2010-09-20 11:27:04  2010-09-20 11:43:56                 31208   
1        61  2010-09-20 11:41:22  2010-09-20 11:42:23                 31209   
2      2690  2010-09-20 12:05:37  2010-09-20 12:50:27                 31600   
3      1406  2010-09-20 12:06:05  2010-09-20 12:29:32                 31600   
4      1413  2010-09-20 12:10:43  2010-09-20 12:34:17                 31100   

                   Start station  End station number  \
0       M St & New Jersey Ave SE               31108   
1                 1st & N St  SE               31209   
2                  5th & K St NW               31100   
3                  5th & K St NW               31602   
4  19th St & Pennsylvania Ave NW               31201   

                     End station Bike number Member type  
0                  4th & M St SW      W00742      Member  
1                 1st & N St  SE      W00032      Member  
2  19th St & Pennsylvania Ave NW      W00993      Member  
3        Park Rd & Holmead Pl NW      W00344      Member  
4                 15th & P St NW      W00883      Member

In [29]:
df.dtypes

Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object

In [30]:
df["Duration"].describe()

count    115597.000000
mean       1254.649956
std        2914.317998
min          60.000000
25%         403.000000
50%         665.000000
75%        1120.000000
max       85644.000000
Name: Duration, dtype: float64

In [31]:
df=df.drop('Start date',axis=1)
df=df.drop('End date',axis=1)
df=df.drop('Start station',axis=1)
df=df.drop('End station',axis=1)

In [32]:
df

Duration  Start station number  End station number Bike number  \
0           1012                 31208               31108      W00742   
1             61                 31209               31209      W00032   
2           2690                 31600               31100      W00993   
3           1406                 31600               31602      W00344   
4           1413                 31100               31201      W00883   
...          ...                   ...                 ...         ...   
115592      2179                 31110               31623      W00859   
115593       953                 31106               31401      W00914   
115594       737                 31602               31401      W00973   
115595       514                 31111               31202      W01119   
115596     51962                 31111               31111      W00771   

       Member type  
0           Member  
1           Member  
2           Member  
3           Member  
4           Member  
...            ...  
115592      Casual  
115593      Member  
115594      Member  
115595      Member  
115596      Casual  

[115597 rows x 5 columns]

In [33]:
le = LabelEncoder()

In [34]:
le.fit(df["Member type"])

LabelEncoder()

In [35]:
df["Member type"] = le.transform(df["Member type"])

In [36]:
df


Duration  Start station number  End station number Bike number  \
0           1012                 31208               31108      W00742   
1             61                 31209               31209      W00032   
2           2690                 31600               31100      W00993   
3           1406                 31600               31602      W00344   
4           1413                 31100               31201      W00883   
...          ...                   ...                 ...         ...   
115592      2179                 31110               31623      W00859   
115593       953                 31106               31401      W00914   
115594       737                 31602               31401      W00973   
115595       514                 31111               31202      W01119   
115596     51962                 31111               31111      W00771   

        Member type  
0                 1  
1                 1  
2                 1  
3                 1  
4                 1  
...             ...  
115592            0  
115593            1  
115594            1  
115595            1  
115596            0  

[115597 rows x 5 columns]

In [41]:
le = LabelEncoder();
le.fit(df["Bike number"])
df["Bike number"]=le.transform(df["Bike number"])

In [42]:
df


Duration  Start station number  End station number  Bike number  \
0           1012                 31208               31108          614   
1             61                 31209               31209           41   
2           2690                 31600               31100          836   
3           1406                 31600               31602          282   
4           1413                 31100               31201          734   
...          ...                   ...                 ...          ...   
115592      2179                 31110               31623          716   
115593       953                 31106               31401          764   
115594       737                 31602               31401          819   
115595       514                 31111               31202          946   
115596     51962                 31111               31111          636   

        Member type  
0                 1  
1                 1  
2                 1  
3                 1  
4                 1  
...             ...  
115592            0  
115593            1  
115594            1  
115595            1  
115596            0  

[115597 rows x 5 columns]

In [48]:
train = np.array(df.iloc[0:10000])

In [49]:
test = np.array(df.iloc[100000:,])

In [50]:
test

array([[  167, 31608, 31613,   569,     1],
       [  396, 31619, 31623,   476,     1],
       [ 2528, 31303, 31207,   131,     1],
       ...,
       [  737, 31602, 31401,   819,     1],
       [  514, 31111, 31202,   946,     1],
       [51962, 31111, 31111,   636,     0]], dtype=int64)

In [51]:
train

array([[ 1012, 31208, 31108,   614,     1],
       [   61, 31209, 31209,    41,     1],
       [ 2690, 31600, 31100,   836,     1],
       ...,
       [ 1005, 31003, 31006,    99,     0],
       [ 1624, 31216, 31601,   893,     1],
       [ 6447, 31215, 31215,   864,     0]], dtype=int64)

In [52]:
from sklearn.naive_bayes import GaussianNB

In [53]:
model = GaussianNB()

In [55]:
model.fit(train[:,0:4],train[:,4])

GaussianNB(priors=None, var_smoothing=1e-09)

In [56]:
predicted = model.predict(test[:,0:4])

In [57]:
predicted

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [58]:
count=0                 ### accuracy
for l in range(30597):  
    if(predicted[l]==test[l,4]):
        count=count+1

IndexError: index 15597 is out of bounds for axis 0 with size 15597

In [59]:
count=0          
### accuracy
for l in range(15597):  
    if(predicted[l]==test[l,4]):
        count=count+1

In [60]:
count/15597

0.9097262294030903

NameError: name 'test' is not defined